---
title: 'Scenarios'
teaching: 10
exercises: 2
---

# Scenarios
The scenarios below can inform the development of workflows or research ideas. They aim to leverage the availability and integration of relevant information from different data services. 

## [Prioritising emergency recording of cultural heritage](emergency.md)
Coastal heritage sites face growing threats from erosion, flooding, and climate change, making equitable, data-driven prioritisation of preservation resources essential.


## [Informing planning of infrastructure affecting cultural heritage](planning.md)

Infrastructure near heritage sites boosts tourism and access but risks physical damage and overtourism; decision-makers need better data to balance these pressures.


## [Mitigating the impacts of ageing infrastructure on urban communities](ageing.md)

Urban historic buildings face structural damage from traffic and ageing infrastructure, threatening occupied spaces and requiring better data to guide mitigation planning.


## Mapping Seshat data to historical polities with Cliopatria

Quantitative historical data in Seshat can support powerful comparative research, but the lack of explicit and precise geographic data limits spatial analysis. Combining Seshat with Cliopatria polygon data makes it possible to map polities, identify gaps in coverage, and explore likely transitions between political entities over time. 